# Generated by Django 4.1.6 on 2023-02-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.CharField(choices=[('Teenager (10 - 18)', 'Teenager'), ('Young Adult (19 - 25)', 'Young Adult'), ('Adult (26 - 40)', 'Adult'), ('Middle Aged (41 - 60)', 'Middle Aged'), ('Senior (>61)', 'Senior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_rzzofg', upload_to='images/'),
        ),
    ]
