# Generated by Django 4.1.6 on 2023-02-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_group',
            field=models.CharField(choices=[('Teenager (10 - 18)', 'Teenager'), ('Young Adult (19 - 25)', 'Youngadult'), ('Adult (26 - 40)', 'Adult'), ('Middle Aged (41 - 60)', 'Middleaged'), ('Senior (>61)', 'Senior')], max_length=50),
        ),
    ]
