# Generated by Django 3.2.17 on 2023-02-12 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                ('recommendation', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('owner', 'post'), ('owner', 'recommendation')},
            },
        ),
    ]
