# Generated by Django 3.2.17 on 2023-02-12 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Music', 'Music'), ('Art', 'Art'), ('Person', 'Person'), ('Place', 'Place'), ('Movies', 'Movies'), ('Event', 'Event')], max_length=50)),
                ('price_category', models.CharField(choices=[('Free', 'Free'), ('€', 'Cheap'), ('€€', 'Average'), ('€€€', 'Aboveaverage'), ('€€€€', 'Expensive')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_l2kfwu', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
