# Generated by Django 4.1.6 on 2023-02-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='price_category',
            field=models.CharField(choices=[('Free', 'Free'), ('Cheap (€)', 'Cheap'), ('Average (€€)', 'Average'), ('Above Average (€€€)', 'Aboveaverage'), ('Expensive (€€€€)', 'Expensive')], max_length=50),
        ),
    ]
