# Generated by Django 4.1.6 on 2023-02-24 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('likes_recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likerecommendation',
            name='recommendation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_recommendations', to='recommendations.recommendation'),
        ),
    ]
